# Generated by Django 4.0.4 on 2022-05-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(default='10:28'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='desc',
            field=models.TextField(default='hello world', max_length=122),
            preserve_default=False,
        ),
    ]
