# Generated by Django 4.0.4 on 2022-05-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_contact_date_contact_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.TextField(),
        ),
    ]
