# Generated by Django 4.0.4 on 2022-05-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_contact_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
